CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'user42';
GRANT ALL PRIVILEGES ON wp.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON phpmyadmin.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON phpmyadmin.* TO 'pma'@'%' IDENTIFIED BY 'pmapass';
FLUSH PRIVILEGES;
