#secretGenerator:
#- name: mysql-pass
#  literals:
#  - password=user42
resources:
  - metallb.yaml
  - secret.yaml
  - influxdb.yaml
  - mysql.yaml
  - nginx.yaml
  - ftps.yaml
  - wordpress.yaml
  - phpmyadmin.yaml
  - grafana.yaml
