secretGenerator:
- name: mysql-pass
  literals:
  - password=user42
resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
  - metallb.yaml
  - nginx.yaml
#  - mysql.yaml
#  - wordpress.yaml
