apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "ip-share"
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: nginx-https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: nginx-ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: nginx-http
        - containerPort: 443
          name: nginx-https
