apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
    - port: 8086
  selector:
    app: telegraf
    tier: frontend
  clusterIP: None
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: telegraf-pv-claim
#  labels:
#    app: telegraf
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
        tier: frontend
    spec:
      containers:
      - image: telegraf
        imagePullPolicy: Never
        name: telegraf
        env:
        - name: TELEGRAF_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 8086
          name: telegraf
#        volumeMounts:
#        - name: telegraf-persistent-storage
#          mountPath: /var/lib/influxdb
#      volumes:
#      - name: telegraf-persistent-storage
#        persistentVolumeClaim:
#          claimName: telegraf-pv-claim
