apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "ip-share"
  labels:
    app: mysql
spec:
  ports:
    - port: 5050
  selector:
    app: mysql
    tier: wordpress
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: wordpress
    spec:
      containers:
      - image: wordpress
        imagePullPolicy: Never
        name: wordpress
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: DB_USER
          value: root
        - name: DB_NAME
          value: wp
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
